### ISSUE TITLE
ant dist issue

### ISSUE THREAD

**Issue by ant2012** [webdetails/cte#22]
compile.compile:
    [javac] C:\git\pentaho\cte\build-res\subfloor.xml:1081: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 25 source files to C:\git\pentaho\cte\bin\classes

BUILD FAILED
C:\git\pentaho\cte\build-res\subfloor.xml:1081: Error running javac.exe compiler

**Comment by pedrofvteixeira** [comment]
Hi @ant2012 , please check your jdk installation; also, check for additional info related to the error you're getting in lines below those you've pasted

**Comment by ant2012** [comment]
Thanks, it's ok with jdk7
